version: "3"

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - frontend
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    expose:
      - "9000"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    restart: unless-stopped
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    hostname: mariadb
    expose:
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_HOST: wordpress  # Set allowed host

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/inception/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/inception/data/wordpress

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
